name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DPHONK_ENABLE_WARNINGS=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure --build-config Release
